import Navbar from "@/components/Navbar";
import "./globals.css";
import { NextAuthProvider } from "@/providers/Providers";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="bg_radial-gradient w-screen h-screen text-blue">
                <NextAuthProvider>
                    <Navbar />
                    {children}
                </NextAuthProvider>
            </body>
        </html>
    );
}
